### ISSUE TITLE
Odevzdavam svuj první úkol

### ISSUE THREAD

**Issue by PetraZabickova** [PetraZabickova/python_ukol1#1]
Prosím o kontrolu @reezy.kr@gmail.com
Děkuji

**Comment by t-reezy** [comment]
Super! Nemám připomínek, vypadá to super ;) Píšu jako splněno. 
Kdybys ještě chtěla mrknout na bonusy,  abstraktní třída a enum třída, tak určitě můžeš - klidně na to ještě jednou mrknu.
